version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/myapp
hooks:
    BeforeInstall:
    - location: scripts/sap_demo.sh
      timeout: 300
      runas: ec2-user
    AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
